version = 1
SPDX-PackageName = "canvodpy-extensions"
SPDX-PackageSupplier = "Nicolas François Bader <nicolas.bader@tuwien.ac.at>"
SPDX-PackageDownloadLocation = "https://github.com/nfb2021/canvodpy-extensions"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Nicolas François Bader"
SPDX-License-Identifier = "Apache-2.0"
