name: FAIR Software Check

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

permissions: read-all

jobs:
  verify:
    name: "Check FAIR software compliance"
    runs-on: ubuntu-latest
    steps:
      - uses: fair-software/howfairis-github-action@4c11146488125aa6e1531184eed51d781bcd5871  # main
        name: Measure compliance with fair-software.eu recommendations
        env:
          PYCHARM_HOSTED: "Trick colorama into displaying colored output"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          MY_REPO_URL: "https://github.com/${{ github.repository }}"
